...............................F...........F.F...F..........................F....../Users/mike/anaconda/envs/fipy_py27/lib/python2.7/site-packages/past/utils/__init__.py:95: RuntimeWarning: divide by zero encountered in double_scalars
  return a / b
.......................................F..................................F.F........................../Users/mike/anaconda/envs/fipy_py27/lib/python2.7/site-packages/past/utils/__init__.py:95: RuntimeWarning: invalid value encountered in double_scalars
  return a / b
...../Users/mike/Dev/fipy/examples/reactiveWetting/liquidVapor1D.py:3: RuntimeWarning: divide by zero encountered in log
  ##
/Users/mike/Dev/fipy/examples/reactiveWetting/liquidVapor1D.py:18: RuntimeWarning: divide by zero encountered in double_scalars
  # of their official duties.  Pursuant to title 17 Section 105 of the
./Users/mike/Dev/fipy/examples/reactiveWetting/liquidVapor2D.py:3: RuntimeWarning: divide by zero encountered in log
  ##
/Users/mike/Dev/fipy/examples/reactiveWetting/liquidVapor2D.py:22: RuntimeWarning: divide by zero encountered in double_scalars
  # other parties, and makes no guarantees, expressed or implied, about
...
======================================================================
FAIL: tri2Dinput (diffusion.steadyState.mesh1D)
Doctest: diffusion.steadyState.mesh1D.tri2Dinput
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for diffusion.steadyState.mesh1D.tri2Dinput
  File "/Users/mike/Dev/fipy/examples/diffusion/steadyState/mesh1D/tri2Dinput.py", line 6, in tri2Dinput

----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/diffusion/steadyState/mesh1D/tri2Dinput.py", line 37, in diffusion.steadyState.mesh1D.tri2Dinput
Failed example:
    print var.allclose(analyticalArray)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest diffusion.steadyState.mesh1D.tri2Dinput[4]>", line 1
        print var.allclose(analyticalArray)
                ^
    SyntaxError: invalid syntax


======================================================================
FAIL: tri2D (diffusion.explicit)
Doctest: diffusion.explicit.tri2D
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for diffusion.explicit.tri2D
  File "/Users/mike/Dev/fipy/examples/diffusion/explicit/tri2D.py", line 6, in tri2D

----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/diffusion/explicit/tri2D.py", line 34, in diffusion.explicit.tri2D
Failed example:
    print var.allclose(answer, rtol = 1e-8)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest diffusion.explicit.tri2D[11]>", line 1
        print var.allclose(answer, rtol = 1e-8)
                ^
    SyntaxError: invalid syntax


======================================================================
FAIL: mixedelement (diffusion.explicit)
Doctest: diffusion.explicit.mixedelement
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for diffusion.explicit.mixedelement
  File "/Users/mike/Dev/fipy/examples/diffusion/explicit/mixedelement.py", line 6, in mixedelement

----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/diffusion/explicit/mixedelement.py", line 37, in diffusion.explicit.mixedelement
Failed example:
    print var.allclose(answer)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest diffusion.explicit.mixedelement[12]>", line 1
        print var.allclose(answer)
                ^
    SyntaxError: invalid syntax


======================================================================
FAIL: input4thOrder-line (diffusion.nthOrder)
Doctest: diffusion.nthOrder.input4thOrder-line
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for diffusion.nthOrder.input4thOrder-line
  File "/Users/mike/Dev/fipy/examples/diffusion/nthOrder/input4thOrder-line.py", line 6, in input4thOrder-line

----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/diffusion/nthOrder/input4thOrder-line.py", line 17, in diffusion.nthOrder.input4thOrder-line
Failed example:
    print var.allclose(mesh.cellCenters[0], atol = 10)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest diffusion.nthOrder.input4thOrder-line[1]>", line 1
        print var.allclose(mesh.cellCenters[0], atol = 10)
                ^
    SyntaxError: invalid syntax


======================================================================
FAIL: mesh20x20 (phase.impingement)
Doctest: phase.impingement.mesh20x20
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for phase.impingement.mesh20x20
  File "/Users/mike/Dev/fipy/examples/phase/impingement/mesh20x20.py", line 6, in mesh20x20

----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/phase/impingement/mesh20x20.py", line 227, in phase.impingement.mesh20x20
Failed example:
    data = dump.read(filename, f)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest phase.impingement.mesh20x20[40]>", line 1, in <module>
        data = dump.read(filename, f)
      File "/Users/mike/Dev/fipy/fipy/tools/dump.py", line 119, in read
        f = io.StringIO(data)
    TypeError: initial_value must be unicode or None, not str
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/phase/impingement/mesh20x20.py", line 228, in phase.impingement.mesh20x20
Failed example:
    newPhase = data['phase']
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest phase.impingement.mesh20x20[41]>", line 1, in <module>
        newPhase = data['phase']
    NameError: name 'data' is not defined
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/phase/impingement/mesh20x20.py", line 229, in phase.impingement.mesh20x20
Failed example:
    newTheta = data['theta']
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest phase.impingement.mesh20x20[42]>", line 1, in <module>
        newTheta = data['theta']
    NameError: name 'data' is not defined
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/phase/impingement/mesh20x20.py", line 230, in phase.impingement.mesh20x20
Failed example:
    newThetaEq = buildThetaEquation(newPhase, newTheta)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest phase.impingement.mesh20x20[43]>", line 1, in <module>
        newThetaEq = buildThetaEquation(newPhase, newTheta)
    NameError: name 'newPhase' is not defined
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/phase/impingement/mesh20x20.py", line 231, in phase.impingement.mesh20x20
Failed example:
    newPhaseEq = buildPhaseEquation(newPhase, newTheta)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest phase.impingement.mesh20x20[44]>", line 1, in <module>
        newPhaseEq = buildPhaseEquation(newPhase, newTheta)
    NameError: name 'newPhase' is not defined
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/phase/impingement/mesh20x20.py", line 235, in phase.impingement.mesh20x20
Failed example:
    for i in range(steps // 2):
        newTheta.updateOld()
        newThetaEq.solve(newTheta, dt=timeStepDuration, solver=GeneralSolver(iterations=2000, tolerance=1e-15))
        newPhaseEq.solve(newPhase, dt=timeStepDuration, solver=GeneralSolver(iterations=2000, tolerance=1e-15))
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest phase.impingement.mesh20x20[45]>", line 2, in <module>
        newTheta.updateOld()
    NameError: name 'newTheta' is not defined
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/phase/impingement/mesh20x20.py", line 242, in phase.impingement.mesh20x20
Failed example:
    print newTheta.allclose(testData, rtol=1e-7)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest phase.impingement.mesh20x20[46]>", line 1, in <module>
        print newTheta.allclose(testData, rtol=1e-7)
    NameError: name 'newTheta' is not defined


======================================================================
FAIL: vanLeerUpwind (convection.advection)
Doctest: convection.advection.vanLeerUpwind
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for convection.advection.vanLeerUpwind
  File "/Users/mike/Dev/fipy/examples/convection/advection/vanLeerUpwind.py", line 6, in vanLeerUpwind

----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/convection/advection/vanLeerUpwind.py", line 26, in convection.advection.vanLeerUpwind
Failed example:
    print numerix.allclose(var1.globalValue[nx // 2:3 * nx // 4],
                           var2.globalValue[:nx // 4], atol=1e-6)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest convection.advection.vanLeerUpwind[1]>", line 1
        print numerix.allclose(var1.globalValue[nx // 2:3 * nx // 4],
                    ^
    SyntaxError: invalid syntax
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/convection/advection/vanLeerUpwind.py", line 33, in convection.advection.vanLeerUpwind
Failed example:
    print var1.max() > 0.77
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest convection.advection.vanLeerUpwind[2]>", line 1
        print var1.max() > 0.77
                 ^
    SyntaxError: invalid syntax


======================================================================
FAIL: circle (levelSet.surfactant)
Doctest: levelSet.surfactant.circle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for levelSet.surfactant.circle
  File "/Users/mike/Dev/fipy/examples/levelSet/surfactant/circle.py", line 6, in circle

----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/levelSet/surfactant/circle.py", line 36, in levelSet.surfactant.circle
Failed example:
    print surfactantBefore.allclose(surfactantAfter)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest levelSet.surfactant.circle[4]>", line 1
        print surfactantBefore.allclose(surfactantAfter)
                             ^
    SyntaxError: invalid syntax
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/levelSet/surfactant/circle.py", line 42, in levelSet.surfactant.circle
Failed example:
    print numerix.sqrt(numerix.sum(error) / numerix.sum(error > 0))
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest levelSet.surfactant.circle[9]>", line 1
        print numerix.sqrt(numerix.sum(error) / numerix.sum(error > 0))
                    ^
    SyntaxError: invalid syntax


======================================================================
FAIL: expandingCircle (levelSet.surfactant)
Doctest: levelSet.surfactant.expandingCircle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for levelSet.surfactant.expandingCircle
  File "/Users/mike/Dev/fipy/examples/levelSet/surfactant/expandingCircle.py", line 6, in expandingCircle

----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/levelSet/surfactant/expandingCircle.py", line 41, in levelSet.surfactant.expandingCircle
Failed example:
    print surfactantBefore.allclose(surfactantAfter)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest levelSet.surfactant.expandingCircle[5]>", line 1
        print surfactantBefore.allclose(surfactantAfter)
                             ^
    SyntaxError: invalid syntax
----------------------------------------------------------------------
File "/Users/mike/Dev/fipy/examples/levelSet/surfactant/expandingCircle.py", line 50, in levelSet.surfactant.expandingCircle
Failed example:
    print numerix.sqrt(numerix.sum(error) / numerix.sum(error > 0)) < 0.04
Exception raised:
    Traceback (most recent call last):
      File "/Users/mike/anaconda/envs/fipy_py27/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest levelSet.surfactant.expandingCircle[10]>", line 1
        print numerix.sqrt(numerix.sum(error) / numerix.sum(error > 0)) < 0.04
                    ^
    SyntaxError: invalid syntax


----------------------------------------------------------------------
Ran 195 tests in 446.995s

FAILED (failures=8)
